### ISSUE TITLE
Wrong path to settings

### ISSUE THREAD

**Issue by rchl** [kufii/Sublime-ESLint-Fix#1]
https://github.com/kufii/Sublime-ESLint-Fix/blob/dfb8f56eaef43fe7454b5fbb0c1ed9133ea43cd7/Main.sublime-menu#L23

The path points to `.../eslint-fix/...` while the package is installed as `ESLint Fix.sublime-package` when installed through Package control. That means opening settings will fail due to space/dash difference.

**Comment by kufii** [comment]
thanks a lot for reporting, an update has been pushed to package control
