### ISSUE TITLE
Run node from PATH by default

### ISSUE THREAD

**Issue by rchl** [kufii/Sublime-ESLint-Fix#2]
In my opinion plugin should try to run node without path specified so that PATH is looked up. So it should either iterate through PATHs and look for node binary or execute process with shell=True so that PATH is looked up automatically.

Config should not have node paths defined by default and only when set by the user those should override whatever might be on the PATH.

**Comment by rchl** [comment]
Other sublime packages typically implement function like this one https://github.com/SublimeLinter/SublimeLinter/blob/master/lint/util.py#L186 to find executable on the path.

**Comment by kufii** [comment]
Sure thing, I agree, I'll implement it sometime soon

**Comment by kufii** [comment]
I need to do some additional testing before it's released, but I've implemented this

**Comment by kufii** [comment]
Update is out

**Comment by rchl** [comment]
Thanks :)
