### ISSUE TITLE
Consider passing source to eslint through stdin

### ISSUE THREAD

**Issue by rchl** [kufii/Sublime-ESLint-Fix#3]
Eslint can check code through stdin (https://eslint.org/docs/user-guide/command-line-interface#using-stdin). Have you considered using that (together with `--stdin-filename` as some checks depend on file name) instead of creating temporary files?

I think it might work if you set working directory to the original file's location (so that configuration files are picked up properly).

**Comment by kufii** [comment]
I will investigate this

**Comment by rchl** [comment]
Created pull request #4 with this implemented.

**Comment by kufii** [comment]
I'll close this issue once the change has been published to package control
