### ISSUE TITLE
Path variables to settings not expanded

### ISSUE THREAD

**Issue by bitst0rm** [kufii/Sublime-ESLint-Fix#5]
similar to [issue#1](https://github.com/kufii/Sublime-ESLint-Fix/issues/1)
```
    "local_eslint_path": {
        "osx": "${packages}/local/node_modules/.bin/eslint"
    }
```
path variables `${packages}` will not be expanded and ESLint-Fix will fail to work. A fix would be:
change [line L16](https://github.com/kufii/Sublime-ESLint-Fix/blob/master/src/pathutil.py#L16) from:
```
def expand_path(path):
    return os.path.expanduser(os.path.expandvars(path)) 
```
to:
```
def expand_path(path):
    varx = sublime.active_window().extract_variables()
    path = sublime.expand_variables(path, varx)
    return os.path.expanduser(os.path.expandvars(path))
```
* naming `varx` instead of `vars` to avoid: `pylint: W0622 - Redefining built-in 'vars' (redefined-builtin)`

**Comment by kufii** [comment]
Thanks for reporting this, I've created a new release 1.1.3, it should get pushed to package control shortly
